### PR TITLE
Propagate controller action final state

### PR DESCRIPTION
**Pull request by po1**
This is a proposed fix for #15 

It leaves proper error message and error code generation unimplemented.
Issue #18 has been opened to that effect.

### CODE REVIEW

**Comment by po1** [comment]
@adolfo-rt @v-lopez please review.

**Comment by po1** [comment]
Refactoring of the pull request done.

**Comment by v-lopez** [comment]
Looks good to me.

**Comment by adolfo-rt** [comment]
+1, I saw this working on Friday.

**Pull request merged**
