### PR TITLE
Refactor populateVelocities

### PR DESCRIPTION
**Pull request by po1**
Also added documentation and removed the node greeting log statement ( :crying_cat_face: )

### CODE REVIEW

**Comment by po1** [comment]
@adolfo-rt this pull request would be a good place to add a unit test (#8) :)

**Comment by po1** [comment]
@adolfo-rt please also squash the commits to avoid needlessly cluttering the commit log

**Comment by adolfo-rt** [comment]
Done

**Comment by po1** [comment]
Looks like some other refactoring broke this.
Also, @adolfo-rt, will you have time to implement a unit test for `populateVelocities` this week?

**Comment by adolfo-rt** [comment]
Not that I don't want to do it, but there is no prevision for writing tests in the coming weeks. I was hoping to do this in April or so. My current set of patches to play_motion will need at least a whole week of test writing, maybe more. The `populateVelocities` part could take 1 - 1.5 days.

What broke exactly?

**Comment by po1** [comment]
I'll rebase this PR and fix the conflicts. It is just about code moving around and patches not applying properly.
I will take back the initial suggestion that a unit test (#8) should be done here and merge it early, as I want to make the last release before the merge with the planning branch.

**Comment by adolfo-rt** [comment]
> I will take back the initial suggestion that a unit test (#8) should be done here and merge it early, as I want to make the last release before the merge with the planning branch.

That merge will probably be a painful one.

**Comment by po1** [comment]
Rebased, built, passed the unit tests. Merging.

**Pull request merged**
