### PR TITLE
Add install() rule for headers

### PR DESCRIPTION
**Pull request by po1**
Now that we have a library, we should also install the headers.

### CODE REVIEW

**Comment by po1** [comment]
@adolfo-rt is this good with you?

There are two version of this `install()` rule. I don't remember where I found this one, but the one by default in the `CMakeLists.txt` uses `CATKIN_PACKAGE_INCLUDE_DESTINATION` with `${PROJECT_NAME}` explicitly in the rules.

I find the one that I've used more flexible, but it might not work correctly if for some reason `CATKIN_PACKAGE_INCLUDE_DESTINATION` is not `include/${PROJECT_NAME}`

**Comment by adolfo-rt** [comment]
I'm confused with the previous comment. The PR is using `CATKIN_GLOBAL_INCLUDE_DESTINATION`, not `CATKIN_PACKAGE_INCLUDE_DESTINATION`. What should I give my opinion on?.

**Comment by po1** [comment]
I will clarify:

In other packages, you can find either `CATKIN_GLOBAL_INCLUDE_DESTINATION` or `CATKIN_PACKAGE_INCLUDE_DESTINATION`, depending on the package. Both achieve the same goal, but there is a subtlety.

By default, when you use `catkin_create_pkg`, you will have a commented-out template for the `install()` rule. This template uses `CATKIN_PACKAGE_INCLUDE_DESTINATION`.

You can see the differences below.
- here with `CATKIN_PACKAGE_INCLUDE_DESTINATION`:
  
  ``` cmake
  install(DIRECTORY include/${PROJECT_NAME}/
    DESTINATION ${CATKIN_PACKAGE_INCLUDE_DESTINATION}
    FILES_MATCHING PATTERN "*.h"
  )
  ```
- here with `CATKIN_GLOBAL_INCLUDE_DESTINATION`
  
  ``` cmake
  install(DIRECTORY include/
    DESTINATION ${CATKIN_GLOBAL_INCLUDE_DESTINATION}
    FILES_MATCHING PATTERN "*.h"
  )
  ```

My point was that the latter is more flexible, since it allows for headers not nested under `include/${PROJECT_NAME}` to be installed as well.

This is a detail.

**Comment by adolfo-rt** [comment]
If the behavior is the same as `CATKIN_PACKAGE_INCLUDE_DESTINATION`, but with the added benefit that additional headers (if any) not in `include/${PROJECT_NAME}` are also installed, I say :+1:

**Pull request merged**
