### PR TITLE
Allow cast from int to double in xmlrpc helpers

### PR DESCRIPTION
**Pull request by po1**
This is a fix for #28 

@bmagyar can you try this? I checked that it builds, but can not try it easily on my setup.

### CODE REVIEW

**Comment by bmagyar** [comment]
Doesn't work.
The template specialization for `double` is not called, since `output` is a `ros::Duration`

**Comment by po1** [comment]
I don't see a way to solve this cleanly without adding a template specialization for `ros::Duration`. I'll ask around.

**Comment by po1** [comment]
The problems stems from the fact that the `ros::Duration` constructor accepts a `double`. It can be solved in `play_motion` by explicitly fetching a double and then feeding it to the `ros::Duration`
I will update the PR.

**Comment by po1** [comment]
Tested locally, fixes the bug. Merging.

**Pull request merged**
