### PR TITLE
Add service call to query available motions.

### PR DESCRIPTION
**Pull request by adolfo-rt**

### CODE REVIEW

**Comment by adolfo-rt** [comment]
I'm open to discussing the extracted motion info. Currently it's motion name, duration and joints. Is this fine, or would you rather have more/less info?.

@po1, @v-lopez

**Comment by adolfo-rt** [comment]
One more thing. Because of ros/ros_comm#351, it is not possible to detect updates in the loaded motions list :-(

**Comment by po1** [comment]
We can add something to the `controllerUpdater` to also force get the whole parameter structure regularly.

**Comment by po1** [comment]
@adolfo-rt what is the added value over simply fetching the params from a separate node?

**Comment by adolfo-rt** [comment]
> @adolfo-rt what is the added value over simply fetching the params from a separate node?

Not having to depend on `play_motion` and all its dependencies to get this info. The dependency would be `play_motion_msgs`. The alternative would be to have some of the `play_motion` helpers living in `play_motion_msgs`.

**Comment by po1** [comment]
OK, despite being a service, it looks fine. Merging.

**Pull request merged**
